openapi: 3.0.0
info:
  title: Cart API
  version: 1.0.0
  description: API endpoints for shopping cart management

paths:
  /api/carts:
    post:
      tags:
        - Cart
      summary: Create new cart
      description: Create a new empty shopping cart (Admin only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '401':
          description: Unauthorized
    
    get:
      tags:
        - Cart
      summary: Get all carts
      description: List all shopping carts (Admin only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
        '401':
          description: Unauthorized
    
    delete:
      tags:
        - Cart
      summary: Remove all products
      description: Remove all products from the cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: All products removed from cart
        '401':
          description: Unauthorized

  /api/carts/AddProduct:
    post:
      tags:
        - Cart
      summary: Add product to cart
      description: Add a product to the shopping cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cartId
                - productId
                - quantity
              properties:
                cartId:
                  type: string
                productId:
                  type: string
                quantity:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: Product added to cart successfully
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /api/carts/products/{pid}:
    delete:
      tags:
        - Cart
      summary: Remove specific product
      description: Remove a specific product from the cart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: Product ID to remove
      responses:
        '200':
          description: Product removed from cart successfully
        '404':
          description: Product not found in cart
        '401':
          description: Unauthorized

  /api/carts/purchase:
    post:
      tags:
        - Cart
      summary: Complete purchase
      description: Complete the purchase process for items in cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Purchase completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticket:
                    $ref: '#/components/schemas/Ticket'
                  failedProducts:
                    type: array
                    items:
                      type: string
        '400':
          description: Purchase failed
        '401':
          description: Unauthorized

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: Cart unique identifier
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: Reference to product ID
              quantity:
                type: integer
                minimum: 1
        user:
          type: string
          description: Reference to user ID

    Ticket:
      type: object
      properties:
        _id:
          type: string
        code:
          type: string
        purchase_datetime:
          type: string
          format: date-time
        amount:
          type: number
        purchaser:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT